fileUrl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
dir.create("./data")
download.file(fileUrl, destfile="./data/dataarchive.zip")
unzip("./data/dataarchive.zip", exdir="./data/UCI_HAR")
train <- read.table("./data/UCI_HAR/UCI HAR Dataset/train/X_train.txt")
train_y <- read.table("./data/UCI_HAR/UCI HAR Dataset/train/y_train.txt")
train_subject <- read.table("./data/UCI_HAR/UCI HAR Dataset/train/subject_train.txt")
test <- read.table("./data/UCI_HAR/UCI HAR Dataset/test/X_test.txt")
test <- read.table("./data/UCI_HAR/UCI HAR Dataset/test/X_test.txt")
test_y <- read.table("./data/UCI_HAR/UCI HAR Dataset/test/y_test.txt")
test_subject <- read.table("./data/UCI_HAR/UCI HAR Dataset/test/subject_test.txt")
labels <- read.table("./data/UCI_HAR/UCI HAR Dataset/activity_labels.txt")
features <- read.table("./data/UCI_HAR/UCI HAR Dataset/features.txt")
library(dplyr)
test_y <- mutate(test_y, activity = ifelse(V1==1,"walk",
                                    ifelse(V1==2, "walk_up",
                                    ifelse(V1==3, "walk_down",
                                    ifelse(V1==4, "sit",
                                    ifelse(V1==5, "stand",
                                    ifelse(V1==6, "lay", NA)))))))
id_test <- cbind(test_subject, test_y[2])
colnames(id_test) <- c("subject", "activity")
id_test$activity <- as.factor(id_test$activity)
list_features <- as.vector(features$V2)
colnames(test) <- list_features
testdata <- cbind(id_test,test)
train_y <- mutate(train_y, activity = ifelse(V1==1,"walk",
                                    ifelse(V1==2, "walk_up",
                                    ifelse(V1==3, "walk_down",
                                    ifelse(V1==4, "sit",
                                    ifelse(V1==5, "stand",
                                    ifelse(V1==6, "lay", NA)))))))
id_train <- cbind(train_subject, train_y[2])
colnames(id_train) <- c("subject", "activity")
id_train$activity <- as.factor(id_train$activity)
list_features <- as.vector(features$V2)
colnames(train) <- list_features
traindata <- cbind(id_train,train)
fulldata <- rbind(testdata, traindata)
str(fulldata)
data_no_dups <- fulldata[,!duplicated(colnames(fulldata))]
meanvars <- select(data_no_dups, contains("mean"))
stdvars <- select(data_no_dups, contains("std"))
id_full <- select(data_no_dups, 1:2)
data_mean_std <- cbind(id_full, meanvars, stdvars)
Header <- c("subject", "activity", 
            "meanX_tBodyAccelerometer",
            "meanY_tBodyAccelerometer",
            "meanZ_tBodyAccelerometer",
            "meanX_tGravityAccelerometer",
            "meanY_tGravityAccelerometer",
            "meanZ_tGravityAccelerometer",
            "meanX_tBodyAccelerometerJerk",
            "meanY_tBodyAccelerometerJerk",
            "meanZ_tBodyAccelerometerJerk",
            "meanX_tBodyGyroscope",
            "meanY_tBodyGyroscope",
            "meanZ_tBodyGyroscope",
            "meanX_tBodyGyroscopeJerk",
            "meanY_tBodyGyroscopeJerk",
            "meanZ_tBodyGyroscopeJerk",
            "mean_tBodyAcceleratorMag",
            "mean_tGravityAcceleratorMag",
            "mean_tBodyAcceleratoryJerkMag",
            "mean_tBodyGryroscopeMag",
            "mean_tBodyGyroscopeJerkMag",
            "meanX_fBodyAccelerator",
            "meanY_fBodyAccelerator",
            "meanZ_fBodyAccelerator",
            "meanfX_fBodyAccelerator",
            "meanfY_fBodyAccelerator",
            "meanfZ_fBodyAccelerator",
            "meanX_fBodyAcceleratorJerk",
            "meanY_fBodyAcceleratorJerk",
            "meanZ_fBodyAcceleratorJerk",
            "meanfX_fBodyAcceleratorJerk",
            "meanfY_fBodyAcceleratorJerk",
            "meanfZ_fBodyAcceleratorJerk",
            "meanX_fBodyGyroscope",
            "meanY_fBodyGyroscope",
            "meanZ_fBodyGyroscope",
            "meanfX_fBodyGyroscope",
            "meanfY_fBodyGyroscope",
            "meanfZ_fBodyGyroscope",
            "mean_fBodyAcceleratorMag",
            "meanf_fBodyAcceleratorMag",
            "mean_fBodyBodyAcceleratorJerkMag",
            "meanf_fBodyBodyAcceleratorJerkMag",
            "mean_fBodyBodyGyroscopeMag",
            "meanf_fBodyBodyGyroscopeMag",
            "mean_fBodyBodyGyroscopeJerkMag",
            "meanf_fBodyBodyGyroscopeJerkMag",
            "angle_tBodyAccMean_gravity",
            "angle_tBodyAcckJerkMean_gravityMean",
            "angle_tBodyGyroMean_gravityMean",
            "angle_tBodyGyroJerkMean_gravityMean",
            "angle_X_gravityMean",
            "angle_Y_gravityMean",
            "angle_Z_gravityMean",
            "stdX_tBodyAccelerator",
            "stdY_tBodyAccelerator",
            "stdZ_tBodyAccelerator",
            "stdX_tGravityAccelerator",
            "stdY_tGravityAccelerator",
            "stdZ_tGravityAccelerator",
            "stdX_tBodyAcceleratorJerk",
            "stdY_tBodyAcceleratorJerk",
            "stdZ_tBodyAcceleratorJerk",
            "stdX_tBodyGyroscope",
            "stdY_tBodyGyroscope",
            "stdZ_tBodyGyroscope",
            "stdX_tBodyGyroscopeJerk",
            "stdY_tBodyGyroscopeJerk",
            "stdZ_tBodyGyroscopeJerk",
            "std_tBodyAcceleratorMag",
            "std_tGravityAcceleratorMag",
            "std_tBodyAcceleratorJerkMag",
            "std_tBodyGyroscopeMag",
            "std_tBodyGyroscopeJerkMag",
            "stdX_fBodyAccelerator",
            "stdY_fBodyAccelerator",
            "stdZ_fBodyAccelerator",
            "stdX_fBodyAcceleratorJerk",
            "stdY_fBodyAcceleratorJerk",
            "stdZ_fBodyAcceleratorJerk",
            "stdX_fBodyGyroscope",
            "stdY_fBodyGyroscope",
            "stdZ_fBodyGyroscope",
            "std_fBodyAcceleratorMag",
            "std_fBodyAcceleratorJerkMag",
            "std_fBodyBodyGyroscopeMag",
            "std_fBodyBodyGyroscopeJerkMag")
colnames(data_mean_std) <- Header            
group_means <- group_by(data_mean_std, subject, activity)
tidy_group_means <- summarize(group_means, 
                              groupmeanX_tBodyAccelerometer=mean(meanX_tBodyAccelerometer),
                              groupmeanY_tBodyAccelerometer=mean(meanY_tBodyAccelerometer),
                              groupmeanZ_tBodyAccelerometer=mean(meanZ_tBodyAccelerometer),
                              groupmeanX_tGravityAccelerometer=mean(meanX_tGravityAccelerometer),
                              groupmeanY_tGravityAccelerometer=mean(meanY_tGravityAccelerometer),
                              groupmeanZ_tGravityAccelerometer=mean(meanZ_tGravityAccelerometer),
                              groupmeanX_tBodyAccelerometerJerk=mean(meanX_tBodyAccelerometerJerk),
                              groupmeanY_tBodyAccelerometerJerk=mean(meanY_tBodyAccelerometerJerk),
                              groupmeanZ_tBodyAccelerometerJerk=mean(meanZ_tBodyAccelerometerJerk),
                              groupmeanX_tBodyGyroscope=mean(meanX_tBodyGyroscope),
                              groupmeanY_tBodyGyroscope=mean(meanY_tBodyGyroscope),
                              groupmeanZ_tBodyGyroscope=mean(meanZ_tBodyGyroscope),
                              groupmeanX_tBodyGyroscopeJerk=mean(meanX_tBodyGyroscopeJerk),
                              groupmeanY_tBodyGyroscopeJerk=mean(meanY_tBodyGyroscopeJerk),
                              groupmeanZ_tBodyGyroscopeJerk=mean(meanZ_tBodyGyroscopeJerk),
                              groupmean_tBodyAcceleratorMag=mean(mean_tBodyAcceleratorMag),
                              groupmean_tGravityAcceleratorMag=mean(mean_tGravityAcceleratorMag),
                              groupmean_tBodyAcceleratoryJerkMag=mean(mean_tBodyAcceleratoryJerkMag),
                              groupmean_tBodyGryroscopeMag=mean(mean_tBodyGryroscopeMag),
                              groupmean_tBodyGyroscopeJerkMag=mean(mean_tBodyGyroscopeJerkMag),
                              groupmeanX_fBodyAccelerator=mean(meanX_fBodyAccelerator),
                              groupmeanY_fBodyAccelerator=mean(meanY_fBodyAccelerator),
                              groupmeanZ_fBodyAccelerator=mean(meanZ_fBodyAccelerator),
                              groupmeanfX_fBodyAccelerator=mean(meanfX_fBodyAccelerator),
                              groupmeanfY_fBodyAccelerator=mean(meanfY_fBodyAccelerator),
                              groupmeanfZ_fBodyAccelerator=mean(meanfZ_fBodyAccelerator),
                              groupmeanX_fBodyAcceleratorJerk=mean(meanX_fBodyAcceleratorJerk),
                              groupmeanY_fBodyAcceleratorJerk=mean(meanY_fBodyAcceleratorJerk),
                              groupmeanZ_fBodyAcceleratorJerk=mean(meanZ_fBodyAcceleratorJerk),
                              groupmeanfX_fBodyAcceleratorJerk=mean(meanfX_fBodyAcceleratorJerk),
                              groupmeanfY_fBodyAcceleratorJerk=mean(meanfY_fBodyAcceleratorJerk),
                              groupmeanfZ_fBodyAcceleratorJerk=mean(meanfZ_fBodyAcceleratorJerk),
                              groupmeanX_fBodyGyroscope=mean(meanX_fBodyGyroscope),
                              groupmeanY_fBodyGyroscope=mean(meanY_fBodyGyroscope),
                              groupmeanZ_fBodyGyroscope=mean(meanZ_fBodyGyroscope),
                              groupmeanfX_fBodyGyroscope=mean(meanfX_fBodyGyroscope),
                              groupmeanfY_fBodyGyroscope=mean(meanfY_fBodyGyroscope),
                              groupmeanfZ_fBodyGyroscope=mean(meanfZ_fBodyGyroscope),
                              greoupmean_fBodyAcceleratorMag=mean(mean_fBodyAcceleratorMag),
                              groupmeanf_fBodyAcceleratorMag=mean(meanf_fBodyAcceleratorMag),
                              groupmean_fBodyBodyAcceleratorJerkMag=mean(mean_fBodyBodyAcceleratorJerkMag),
                              groupmeanf_fBodyBodyAcceleratorJerkMag=mean(meanf_fBodyBodyAcceleratorJerkMag),
                              groupmean_fBodyBodyGyroscopeMag=mean(mean_fBodyBodyGyroscopeMag),
                              groupmeanf_fBodyBodyGyroscopeMag=mean(meanf_fBodyBodyGyroscopeMag),
                              groupmean_fBodyBodyGyroscopeJerkMag=mean(mean_fBodyBodyGyroscopeJerkMag),
                              groupmeanf_fBodyBodyGyroscopeJerkMag=mean(meanf_fBodyBodyGyroscopeJerkMag),
                              groupangle_tBodyAccMean_gravity=mean(angle_tBodyAccMean_gravity),
                              groupangle_tBodyAcckJerkMean_gravityMean=mean(angle_tBodyAcckJerkMean_gravityMean),
                              groupangle_tBodyGyroMean_gravityMean=mean(angle_tBodyGyroMean_gravityMean),
                              groupangle_tBodyGyroJerkMean_gravityMean=mean(angle_tBodyGyroJerkMean_gravityMean),
                              groupangle_X_gravityMean=mean(angle_X_gravityMean),
                              groupangle_Y_gravityMean=mean(angle_Y_gravityMean),
                              groupangle_Z_gravityMean=mean(angle_Z_gravityMean),
                              groupstdX_tBodyAccelerator=mean(stdX_tBodyAccelerator),
                              groupstdY_tBodyAccelerator=mean(stdY_tBodyAccelerator),
                              groupstdZ_tBodyAccelerator=mean(stdZ_tBodyAccelerator),
                              groupstdX_tGravityAccelerator=mean(stdX_tGravityAccelerator),
                              groupstdY_tGravityAccelerator=mean(stdY_tGravityAccelerator),
                              groupstdZ_tGravityAccelerator=mean(stdZ_tGravityAccelerator),
                              groupstdX_tBodyAcceleratorJerk=mean(stdX_tBodyAcceleratorJerk),
                              groupstdY_tBodyAcceleratorJerk=mean(stdY_tBodyAcceleratorJerk),
                              groupstdZ_tBodyAcceleratorJerk=mean(stdZ_tBodyAcceleratorJerk),
                              groupstdX_tBodyGyroscope=mean(stdX_tBodyGyroscope),
                              groupstdY_tBodyGyroscope=mean(stdY_tBodyGyroscope),
                              groupstdZ_tBodyGyroscope=mean(stdZ_tBodyGyroscope),
                              groupstdX_tBodyGyroscopeJerk=mean(stdX_tBodyGyroscopeJerk),
                              groupstdY_tBodyGyroscopeJerk=mean(stdY_tBodyGyroscopeJerk),
                              groupstdZ_tBodyGyroscopeJerk=mean(stdZ_tBodyGyroscopeJerk),
                              groupstd_tBodyAcceleratorMag=mean(std_tBodyAcceleratorMag),
                              groupstd_tGravityAcceleratorMag=mean(std_tGravityAcceleratorMag),
                              groupstd_tBodyAcceleratorJerkMag=mean(std_tBodyAcceleratorJerkMag),
                              groupstd_tBodyGyroscopeMag=mean(std_tBodyGyroscopeMag),
                              groupstd_tBodyGyroscopeJerkMag=mean(std_tBodyGyroscopeJerkMag),
                              groupstdX_fBodyAccelerator=mean(stdX_fBodyAccelerator),
                              groupstdY_fBodyAccelerator=mean(stdY_fBodyAccelerator),
                              groupstdZ_fBodyAccelerator=mean(stdZ_fBodyAccelerator),
                              groupstdX_fBodyAcceleratorJerk=mean(stdX_fBodyAcceleratorJerk),
                              groupstdY_fBodyAcceleratorJerk=mean(stdY_fBodyAcceleratorJerk),
                              groupstdZ_fBodyAcceleratorJerk=mean(stdZ_fBodyAcceleratorJerk),
                              groupstdX_fBodyGyroscope=mean(stdX_fBodyGyroscope),
                              groupstdY_fBodyGyroscope=mean(stdY_fBodyGyroscope),
                              groupstdZ_fBodyGyroscope=mean(stdZ_fBodyGyroscope),
                              groupstd_fBodyAcceleratorMag=mean(std_fBodyAcceleratorMag),
                              groupstd_fBodyAcceleratorJerkMag=mean(std_fBodyAcceleratorJerkMag),
                              groupstd_fBodyBodyGyroscopeMag=mean(std_fBodyBodyGyroscopeMag),
                              groupstd_fBodyBodyGyroscopeJerkMag=mean(std_fBodyBodyGyroscopeJerkMag))
write.table(tidy_group_means, "tidy_group_means.txt", row.names=FALSE)